export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST';
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS';
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
